FROM ubuntu:16.04
RUN apt-get -y update; apt-get -y install python-pip git; apt-get -y clean; pip install -U pip; pip install -U ansible
WORKDIR /bio-ansible
ADD . /bio-ansible/
RUN ansible-playbook -i hosts common.yml --tags apt
RUN ansible-playbook -i hosts common.yml; ansible-playbook -i hosts bio.yml
RUN rm -rf /bio-ansbile
