FROM ubuntu:16.04
RUN apt-get -y update && \
    apt-get -y install python-pip git && \
    apt-get -y clean && \
    pip install -U pip && \
    pip install -U ansible
WORKDIR /bio-ansible
ADD . /bio-ansible/
RUN ansible-playbook -c local -i hosts common.yml --tags apt -vvv
RUN ansible-playbook -c local -i hosts common.yml --tags pip -vvv
RUN ansible-playbook -c local -i hosts common.yml --skip-tags apt,pip -vvv
RUN ansible-playbook -c local -i hosts bio.yml --tags r_base,r_extras -vvv
RUN ansible-playbook -c local -i hosts bio.yml --tags blast -vvv
RUN ansible-playbook -c local -i hosts bio.yml --skip-tags r_base,r_extras,blast -vvv
RUN rm -rf /bio-ansbile && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
