FROM ubuntu:16.04
RUN apt-get -y update && \
    apt-get -y install python-pip python-virtualenv python3-pip python3-virtualenv \
                       git default-jdk ant golang-go unzip \
                       zlib1g-dev libncurses-dev libbz2-dev liblzma-dev \
                       tcl lua5.2 liblua5.2-dev lua-filesystem lua-posix && \
    apt-get -y clean && \
    pip install -U pip && \
    pip install -U ansible
# RUN git clone https://github.com/MonashBioinformaticsPlatform/bio-ansible.git
ADD . /bio-ansible/
WORKDIR /bio-ansible

RUN mkdir -p /bioansible/software/modules
RUN mkdir -p /bioansible/software/source
RUN mkdir -p /bioansible/software/apps

RUN ansible-playbook --extra-vars="main_guy=root \
              sudo_guy=root \
              local_home=/root \
              bioansible_basepath=/bioansible \
              source_dir=/bioansible/software/source \
              modules_dir=/bioansible/software/modules \
              modules_core=/bioansible/software/modules/core \
              modules_bio=/bioansible/software/modules/bio \
              modules_extra=/bioansible/software/modules/extra \
              apps_dir=/bioansible/software/apps" \
              -vvv -i hosts common.yml --tags lmod_etc,environment
RUN ansible-playbook --extra-vars="main_guy=root \
              sudo_guy=root \
              local_home=/root \
              bioansible_basepath=/bioansible \
              source_dir=/bioansible/software/source \
              modules_dir=/bioansible/software/modules \
              modules_core=/bioansible/software/modules/core \
              modules_bio=/bioansible/software/modules/bio \
              modules_extra=/bioansible/software/modules/extra \
              apps_dir=/bioansible/software/apps" \
              -vvv -i hosts bio.yml --tags lmod
RUN ansible-playbook --extra-vars="main_guy=root \
              sudo_guy=root \
              local_home=/root \
              bioansible_basepath=/bioansible \
              source_dir=/bioansible/software/source \
              modules_dir=/bioansible/software/modules \
              modules_core=/bioansible/software/modules/core \
              modules_bio=/bioansible/software/modules/bio \
              modules_extra=/bioansible/software/modules/extra \
              apps_dir=/bioansible/software/apps" \
              -vvv -i hosts bio.yml --tags bds
RUN ansible-playbook --extra-vars="main_guy=root \
              sudo_guy=root \
              local_home=/root \
              bioansible_basepath=/bioansible \
              source_dir=/bioansible/software/source \
              modules_dir=/bioansible/software/modules \
              modules_core=/bioansible/software/modules/core \
              modules_bio=/bioansible/software/modules/bio \
              modules_extra=/bioansible/software/modules/extra \
              apps_dir=/bioansible/software/apps" \
              -vvv -i hosts bio.yml \
              --tags bedtools
RUN ansible-playbook --extra-vars="main_guy=root \
              sudo_guy=root \
              local_home=/root \
              bioansible_basepath=/bioansible \
              source_dir=/bioansible/software/source \
              modules_dir=/bioansible/software/modules \
              modules_core=/bioansible/software/modules/core \
              modules_bio=/bioansible/software/modules/bio \
              modules_extra=/bioansible/software/modules/extra \
              apps_dir=/bioansible/software/apps" \
              -vvv -i hosts bio.yml \
              --tags rnasik,star,subread,samtools,htslib,picard,qualimap,fastqc,multiqc && \
    rm -rf /bio-ansible && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY docker/rnasik_wrapper.sh /bioansible/software/apps/rnasik.sh
RUN chmod +x /bioansible/software/apps/rnasik.sh
ENTRYPOINT ["/bioansible/software/apps/rnasik.sh"]
