---

- name: Check that /usr/bin/java exists
  tags: ["always", "java"]
  command: "/usr/bin/java -version"
  register: system_java_check
  ignore_errors: true

- name: Set system_java variable
  tags: ["always", "java"]
  set_fact: system_java='system_java_check and (java_flavour == "oracle_ppa" or java_flavour == "distro")'

- name: Check Oracle Java LMOD module exists
  tags: ["always", "java"]
  stat:
    path: "{{ apps_dir }}/jdk1.{{ jdk_major }}.0_{{ jdk_minor }}"
  register: lmod_oracle_java_check

- name: Set lmod_oracle_java variable
  tags: ["always", "java"]
  set_fact: lmod_oracle_java='lmod_oracle_java_check.stat.isdir and java_flavour == "oracle_tarball"'


- name: download BigDataScript {{ version }}
  tags: bds
  git:
    repo: https://github.com/pcingola/BigDataScript.git
    dest: "{{ source_dir }}/BigDataScript-{{ version }}"
    version: "v{{ version }}"
    update: no

- name: build BigDataScript {{ version }} with system_java
  tags: bds
  shell: cd {{ source_dir }}/BigDataScript-{{ version }}/; ./scripts/install.sh
  args:
    creates: "{{ local_home }}/.bds/bds"
  when: system_java and not lmod_oracle_java

- name: build BigDataScript {{ version }} with lmod_oracle_java
  tags: bds
  shell: export JAVA_HOME={{ apps_dir }}/jdk1.{{ jdk_major }}.0_{{ jdk_minor }}; cd {{ source_dir }}/BigDataScript-{{ version }}/; ./scripts/install.sh
  args:
    creates: "{{ local_home }}/.bds/bds"
  when: lmod_oracle_java

- name: moving executable bds {{ version }} to apps directory
  tags: bds
  shell: mv "{{ local_home }}/.bds" "{{ apps_dir }}/BigDataScript-{{ version }}"
  args:
    creates: "{{ apps_dir }}/BigDataScript-{{ version }}/bds"

- name: copy bds.config template file
  tags: bds
  template:
    src: bds.config.j2
    dest: "{{ apps_dir }}/BigDataScript-{{ version }}/bds.config"
  when: not is_slurm_cluster

- name: copy bds.config template file
  tags: bds
  template:
    src: bds.config-slurm.j2
    dest: "{{ apps_dir }}/BigDataScript-{{ version }}/bds.config"
  when: is_slurm_cluster

- name: Create SLURM wrapper script directory
  tags: bds
  file: path="{{ apps_dir }}/BigDataScript-{{ version }}/clusterGenericSLURM" state=directory
  when: is_slurm_cluster

- name: copy clusterGeneric wrapper scripts
  tags: bds
  template:
    src: "{{ item }}"
    dest: "{{ apps_dir }}/BigDataScript-{{ version }}/clusterGenericSLURM/{{ item | basename | regex_replace('.j2','') }}"
    mode: "u=rwx,g=rwx,o=rx"
  with_fileglob:
    - templates/clusterGenericSLURM/*
  when: is_slurm_cluster

- name: Chmod BigDataScript module directory
  tags: bds
  file:
    dest: "{{ modules_bio }}/BigDataScript"
    state: directory
    mode: 0755

- name: BigDataScript {{ version }} lmod definition
  tags: bds
  template:
    src: sw-module.lua.j2
    dest: "{{ modules_bio }}/BigDataScript/{{ version }}.lua"
    owner: "{{ main_guy }}"
    mode: 0644
  with_items:
    - dir: 'BigDataScript-{{ version }}'
      java: true
      skip_bin: true
      help_text: 'This module loads BigDataScript'

- name: Setting register for BigDataScript {{ version }}
  tags: bds
  stat:
    path: "{{ apps_dir }}/BigDataScript-{{ version }}/bds"
  register: b

- name: Removing BigDataScript {{ version }} source directory
  tags: bds
  file:
    dest: "{{ source_dir }}/BigDataScript-{{ version }}"
    state: absent
  when: "{{ del_src }} b.stat.exists"
