---
- name: Add the Ceph Debian repo
  tags: ['cephfs', 'storage']
  apt_repository: repo="deb https://download.ceph.com/debian-{{ cephfs_version_codename }}/ {{ ansible_distribution_release }} main"
                  state=present

- name: Install CephFS
  tags: ['cephfs', 'storage']
  apt: pkg={{ items }}
  with_items:
    - ceph-fuse
    - ceph-common
